services:
  sentinel-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sentinel-api

    ports:
      - "8000:8000"

    environment:
      SENTINEL_API_KEY: ${SENTINEL_API_KEY}

    volumes:
      - ./data:/app/data

    restart: unless-stopped