"""Security alert model."""

from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class AlertSeverity(StrEnum):
    """Severity levels for security alerts."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(BaseModel):
    """A security alert generated by a detection rule."""

    model_config = ConfigDict(extra="forbid")

    id: str
    rule_id: str
    title: str
    description: str

    severity: AlertSeverity
    risk_score: int = Field(ge=0, le=100)

    source_ip: str | None = None
    username: str | None = None

    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    event_ids: list[str] = Field(default_factory=list)
